### ISSUE TITLE
error in cmd.LoadLicenseToken

### ISSUE THREAD

**Issue by j0nl1** [inlets/inlets-pro-pkg#3]
I don't know why this happening but it crash randomly. I just let the log here.

```
2019/12/17 22:38:21 Welcome to inlets-pro!
2019/12/17 22:38:21 Starting client - version dev
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x319e14]

goroutine 1 [running]:
github.com/alexellis/inlets-pro/cmd.LoadLicenseToken(0xbefe1826, 0x15e, 0x432418, 0xf0, 0x80, 0x0, 0x0)
	/go/src/github.com/alexellis/inlets-pro/cmd/client.go:242 +0x15c
github.com/alexellis/inlets-pro/cmd.runClient(0x6afe08, 0x1070c20, 0x0, 0x4, 0x0, 0x0)
	/go/src/github.com/alexellis/inlets-pro/cmd/client.go:97 +0x314
github.com/alexellis/inlets-pro/vendor/github.com/spf13/cobra.(*Command).execute(0x6afe08, 0x1070be0, 0x4, 0x4, 0x6afe08, 0x1070be0)
	/go/src/github.com/alexellis/inlets-pro/vendor/github.com/spf13/cobra/command.go:826 +0x364
github.com/alexellis/inlets-pro/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x6aff48, 0x0, 0x1, 0x118e8)
	/go/src/github.com/alexellis/inlets-pro/vendor/github.com/spf13/cobra/command.go:914 +0x20c
github.com/alexellis/inlets-pro/vendor/github.com/spf13/cobra.(*Command).Execute(0x6aff48, 0x1, 0x0)
	/go/src/github.com/alexellis/inlets-pro/vendor/github.com/spf13/cobra/command.go:864 +0x1c
github.com/alexellis/inlets-pro/cmd.Execute(0x42c0b7, 0x0, 0x42c0b6, 0x0, 0x432418, 0xf0, 0x106a030, 0x0)
	/go/src/github.com/alexellis/inlets-pro/cmd/inlets.go:56 +0x98
main.main()
	/go/src/github.com/alexellis/inlets-pro/main.go:18 +0x5c
```

**Comment by alexellis** [comment]
It looks like you may have an invalid license. Did it expire? You can check on jwt.io

**Comment by alexellis** [comment]
Feel free to follow-up on email to alex@openfaas.com thanks

**Comment by alexellis** [comment]
What did you get on jwt.io, was it expired?

**Comment by alexellis** [comment]
> 2019/12/17 22:38:21 Starting client - version dev

It looks like you may be using an invalid version of inlets-pro, where did you obtain this binary? It should always have a specific version. One of the packages there looks out of date, too.

**Comment by j0nl1** [comment]
Yes, it was expired. I sent you an email asking for a new license.

**Comment by alexellis** [comment]
That's odd because I did the same:

```
$ wget https://github.com/inlets/inlets-pro-pkg/releases/download/0.4.3/inlets-pro
$ ./inlets-pro version
 _       _      _            _
(_)_ __ | | ___| |_ ___   __| | _____   __
| | '_ \| |/ _ \ __/ __| / _` |/ _ \ \ / /
| | | | | |  __/ |_\__ \| (_| |  __/\ V /
|_|_| |_|_|\___|\__|___(_)__,_|\___| \_/

PRO edition

Version: 0.4.3
Git Commit: 8ae57195013eeecf73eca6528c8db8dfb54567ff
```

Perhaps it was updated since you downloaded last, can you try the latest version too with the key I just issued?

**Comment by j0nl1** [comment]
Yes probably was that, I'm gonna try it with the latest version

Thanks
